global:
  scrape_interval:     15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-exporter'
    metrics_path: '/metrics'
    honor_labels: true
    scrape_interval: 5s
    # scrape_timeout: 60s
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]

  - job_name: 'file-api-spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    scheme: https
    tls_config:
      ca_file: /opt/ca.pem
    static_configs:
      - targets: ['file-api:8443']

  - job_name: 'message-pcs-spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    scheme: https
    tls_config:
      ca_file: /opt/ca.pem
    static_configs:
      - targets: ['message-pcs:8443']

  - job_name: 'message-push-api-spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    scheme: https
    tls_config:
      ca_file: /opt/ca.pem
    static_configs:
      - targets: ['message-push-api:8443']

  - job_name: 'message-receiver-api-spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    scheme: https
    tls_config:
      ca_file: /opt/ca.pem
    static_configs:
      - targets: ['message-receiver-api:8443']

  - job_name: 'trending-topic-api-spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    scheme: https
    tls_config:
      ca_file: /opt/ca.pem
    static_configs:
      - targets: ['trending-topic-api:8443']

  - job_name: 'user-api-spring-actuator'
    metrics_path: '/actuator/prometheus' # Job to scrape application metrics
    scrape_interval: 5s
    scheme: https
    tls_config:
      ca_file: /opt/ca.pem
    static_configs:
      - targets: ['user-api:8443']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics' # Job to scrape application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['rabbitmq:15692']