{
 "title": "Functional dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Online status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users online",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "users" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "users_online", "legendFormat": "Users online" }
     ]
    },
    {
     "title": "Rooms online",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "rooms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rooms_online" }
     ]
    }
   ]
  },
  { "title": "Input messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Messages input (amount)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(messages_in_amount_total) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages input (amount rate per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "rate(messages_in_amount_total[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages input (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(messages_in_bytes_total) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages input (bytes rate per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(messages_in_bytes_total[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Output messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Messages output (amount)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(messages_out_amount_total) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages output (rate amount per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(messages_out_amount_total[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Messages output (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(messages_out_bytes_total) by (service)",
     "legendFormat": "{{service}} b"
    }
   ]
  },
  {
   "title": "Messages output (rate bytes per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(messages_out_bytes_total[1m])",
     "legendFormat": "{{service}} b/s"
    }
   ]
  }
 ]
}